### ISSUE TITLE
Broken symbolic links to Liberation fonts

### ISSUE THREAD

**Issue by clayote** [flathub/com.calibre_ebook.calibre#119]
Trying to run through the normal flatpak launcher gave inscrutable errors #120, so instead I ran the executable directly:

```
sanotehu@sanotehu-MS-7A31:/usr/share/fonts$ /var/lib/flatpak/app/com.calibre_ebook.calibre/current/active/files/lib/calibre/calibre
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 45, in <module>
  File "site.py", line 41, in main
  File "calibre/gui_launch.py", line 64, in calibre
  File "calibre/gui2/main.py", line 539, in main
  File "calibre/gui2/main.py", line 546, in run_main
  File "calibre/gui2/main.py", line 403, in run_gui
  File "calibre/gui2/main.py", line 408, in run_gui_
  File "calibre/gui2/__init__.py", line 1070, in load_builtin_fonts
  File "calibre/gui2/__init__.py", line 815, in load_builtin_fonts
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/flatpak/app/com.calibre_ebook.calibre/x86_64/stable/9ac01238453e52c215e706af9d8ca90c96fa102a66cc95a09e1ff86941982376/files/lib/calibre/resources/fonts/liberation/LiberationSans-Italic.ttf'
```

I found a bunch of broken symbolic links in that `liberation` folder. They seem to expect the font files to be in `/usr/lib/fonts/liberation-fonts` when, on my system, they are in `/usr/share/fonts/truetype/liberation`

Replacing the `liberation` folder with a symbolic link to `/usr/share/fonts/truetype/liberation` fixed the issue, although flatpak still won't run it.

**Comment by Erick555** [comment]
Inside flatpak container those symlinks point to right thing. Launching flatpak executable directly doesn't make sense.
