### ISSUE TITLE
Problem with DeACSM plugin

### ISSUE THREAD

**Issue by LaHaine** [flathub/com.calibre_ebook.calibre#122]
I've noticed a problem with the DeACSM plugin in combination with running calibre as flatpak. When you install the plugin and press the button 'Import activation from ADE (Wine)' it tries to run a windows program under wine to extract the activation key from an existing Wine installation of 'Adobe Digital Editions'. This fails with an error as the calibre flatpak cannot run wine, it seems that /usr/bin/wine is not in the path:
```
calibre, version 5.35.0
ERROR: Unhandled exception: <b>FileNotFoundError</b>:[Errno 2] No such file or directory: 'wine'

calibre 5.35  embedded-python: True is64bit: True
Linux-5.13.0-1028-oem-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.13.0-1028-oem', '#35-Ubuntu SMP Thu Jan 13 14:03:56 UTC 2022')
Python 3.8.5
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 15)
Traceback (most recent call last):
  File "calibre_plugins.deacsm.config", line 470, in import_activation_from_LinuxWine
    ret, msg = importADEactivationLinuxWine(text)
  File "calibre_plugins.deacsm.libadobeImportAccount", line 38, in importADEactivationLinuxWine
    master_key = GetMasterKey(wine_prefix_path)
  File "calibre_plugins.deacsm.getEncryptionKeyLinux", line 268, in GetMasterKey
    success, data = CryptUnprotectDataExecuteWine(path_to_wine_prefix, key_line, entropy)
  File "calibre_plugins.deacsm.getEncryptionKeyLinux", line 342, in CryptUnprotectDataExecuteWine
    proc = subprocess.Popen(["wine", "decrypt_" + winearch + ".exe" ], shell=False, cwd=moddir, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1702, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'wine'

```
This is not a problem with the manually installed calibre.

**Comment by Erick555** [comment]
yes wine doesn't exist in the sandbox. One could hack around it with making a wrapper like `exec flatpak-spawn --host wine "$@"` (needs `--talk-name=org.freedesktop.Flatpak` permission) and put it somewhere available then add to PATH but it's not doable in generic way.

**Comment by LaHaine** [comment]
Ah, so the flatpak calibre cannot run stuff outside the flatpak world.

**Comment by Erick555** [comment]
That's right. It can't.
