### ISSUE TITLE
Does not start any longer

### ISSUE THREAD

**Issue by jtagcat** [flathub/com.calibre_ebook.calibre#157]
```
$ flatpak run com.calibre_ebook.calibre
Traceback (most recent call last):
  File "calibre/gui2/ui.py", line 137, in __init__
  File "calibre/gui2/ui.py", line 155, in init_iaction
  File "calibre/customize/__init__.py", line 612, in load_actual_plugin
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.opml.ui", line 18, in <module>
    from calibre_plugins.opml.main import OPMLDialog
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.opml.main", line 18, in <module>
    from PyQt4.Qt import (QDialog, QGridLayout, QPushButton, QLabel,
ModuleNotFoundError: No module named 'PyQt4'
Traceback (most recent call last):
  File "calibre/gui2/ui.py", line 137, in __init__
  File "calibre/gui2/ui.py", line 155, in init_iaction
  File "calibre/customize/__init__.py", line 612, in load_actual_plugin
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.xray_creator.ui", line 14, in <module>
    from httplib import HTTPSConnection
ModuleNotFoundError: No module named 'httplib'
```

**Comment by ghisvail** [comment]
Version? Distribution? I can't help much with such limited info.

**Comment by Erick555** [comment]
It may be something with plugins. Maybe try moving `~/.var/app/com.calibre_ebook.calibre/config/calibre/plugins` content somewhere else and start the app.

**Comment by jtagcat** [comment]
`com.calibre_ebook.calibre v6.9.0`

OS is Fedora 37, but it shouldn't matter.

Tried without plugins, does not start. It does start with a clean profile.

**Comment by jtagcat** [comment]
Can observe same behaviour as #158, closing for it.
