### ISSUE TITLE
ImportError: cannot import name 'QRegExpValidator' from 'qt.core' (/app/lib/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/core.pyc) / ModuleNotFoundError: No module named 'PyQt4'

### ISSUE THREAD

**Issue by alexanderadam** [flathub/com.calibre_ebook.calibre#161]
I just updated the flatpak package of Calibre and now I'm getting the exceptions

  `ImportError: cannot import name 'QRegExpValidator' from 'qt.core' (/app/lib/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/core.pyc)`

and

  `ModuleNotFoundError: No module named 'PyQt4'`

when trying to start.

<details>
  <summary>Click to expand</summary>

```
❯ flatpak info com.calibre_ebook.calibre

calibre - The one stop solution to all your e-book needs

          ID: com.calibre_ebook.calibre
         Ref: app/com.calibre_ebook.calibre/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 6.9.0
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 454.5 MB
     Runtime: org.freedesktop.Platform/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: efd49f49d2ace896842392149a38355fcda8d0956740a4b1cec85bb0258db922
      Parent: ec50c128aa71d6ff2f2ad241b3346da06483245b506df9e4b726a0e0bdc65956
     Subject: Update 2 modules (06746424)
        Date: 2022-11-26 17:26:31 +0000


❯ flatpak run com.calibre_ebook.calibre
Qt: Session management error: None of the authentication protocols specified are supported
Failed to initialize plugin: '/home/user/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/BOL_DE.zip'
Failed to initialize plugin: '/home/user/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeDRM.zip'
Failed to initialize plugin: '/home/user/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/Goodreads.zip'
Failed to initialize plugin: '/home/user/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/Kindle and Mobipocket DeDRM.zip'
Traceback (most recent call last):
  File "calibre_plugins.annotations.common_utils", line 33, in <module>
    from PyQt5.uic import compileUi
ImportError: cannot import name 'compileUi' from 'qt.core' (/app/lib/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/core.pyc)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/ui.py", line 137, in __init__
  File "calibre/gui2/ui.py", line 155, in init_iaction
  File "calibre/customize/__init__.py", line 612, in load_actual_plugin
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.annotations.action", line 51, in <module>
    from calibre_plugins.annotations.annotated_books import AnnotatedBooksDialog
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.annotations.annotated_books", line 39, in <module>
    from calibre_plugins.annotations.common_utils import (
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.annotations.common_utils", line 37, in <module>
    from PyQt4.Qt import (Qt, QAction, QApplication,
ModuleNotFoundError: No module named 'PyQt4'
Traceback (most recent call last):
  File "calibre/gui2/ui.py", line 137, in __init__
  File "calibre/gui2/ui.py", line 155, in init_iaction
  File "calibre/customize/__init__.py", line 612, in load_actual_plugin
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.exlibris_plugin.ui", line 15, in <module>
    from calibre_plugins.exlibris_plugin.main import MainDialog
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 199, in exec_module
  File "calibre/customize/zipplugin.py", line 195, in get_code
  File "calibre_plugins.exlibris_plugin.main", line 179
    		self.include_spine.setText(str(newRow + 1))
    ^
TabError: inconsistent use of tabs and spaces in indentation
Traceback (most recent call last):
  File "calibre_plugins.extract_isbn.common_utils", line 18, in <module>
    from PyQt5.Qt import (Qt, QIcon, QPixmap, QLabel, QDialog, QHBoxLayout,
ImportError: cannot import name 'QRegExpValidator' from 'qt.core' (/app/lib/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/core.pyc)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/ui.py", line 137, in __init__
  File "calibre/gui2/ui.py", line 155, in init_iaction
  File "calibre/customize/__init__.py", line 612, in load_actual_plugin
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.extract_isbn.action", line 16, in <module>
    import calibre_plugins.extract_isbn.config as cfg
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.extract_isbn.config", line 24, in <module>
    from calibre_plugins.extract_isbn.common_utils import KeyValueComboBox, KeyboardConfigDialog
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.extract_isbn.common_utils", line 24, in <module>
    from PyQt4 import QtGui
ModuleNotFoundError: No module named 'PyQt4'
Traceback (most recent call last):
  File "calibre_plugins.goodreads_sync.common_utils", line 18, in <module>
    from PyQt5.Qt import (Qt, QIcon, QPixmap, QLabel, QDialog, QHBoxLayout, QProgressBar,
ImportError: cannot import name 'QRegExpValidator' from 'qt.core' (/app/lib/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/core.pyc)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/ui.py", line 137, in __init__
  File "calibre/gui2/ui.py", line 155, in init_iaction
  File "calibre/customize/__init__.py", line 612, in load_actual_plugin
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.goodreads_sync.action", line 22, in <module>
    import calibre_plugins.goodreads_sync.config as cfg
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.goodreads_sync.config", line 38, in <module>
    from calibre_plugins.goodreads_sync.common_utils import (NoWheelComboBox, SizePersistedDialog,
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.goodreads_sync.common_utils", line 24, in <module>
    from PyQt4 import QtGui
ModuleNotFoundError: No module named 'PyQt4'
```

</details>

**Comment by alexanderadam** [comment]
Now it works :shrug:
