### ISSUE TITLE
Calibre fails converting EPUB to MOBI

### ISSUE THREAD

**Issue by dbasinge** [flathub/com.calibre_ebook.calibre#181]
Calibre fails converting EPUB to MOBI

```
calibre, version 6.21.0 (linux, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (Lonely Planet Estonia, Latvia & Lithuania)

Convert book 1 of 1 (Lonely Planet Estonia, Latvia & Lithuania)
Conversion options changed from defaults:
  cover: '/tmp/calibre_6.21.0_tmp_6mldf7c3/wo_x9nb1.jpeg'
  read_metadata_from_opf: '/tmp/calibre_6.21.0_tmp_6mldf7c3/wr2k146h.opf'
  verbose: 2
  output_profile: 'kindle_scribe'
  page_breaks_before: "//*[name()='h1' or name()='h2']"
Resolved conversion options
calibre version: 6.21.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': '/tmp/calibre_6.21.0_tmp_6mldf7c3/wo_x9nb1.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_compress': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x7ff42ee3a530>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'mobi_file_type': 'old',
 'mobi_ignore_margins': False,
 'mobi_keep_original_images': False,
 'mobi_toc_at_start': False,
 'no_chapters_in_toc': False,
 'no_inline_navbars': True,
 'no_inline_toc': False,
 'output_profile': <calibre.customize.profiles.KindleScribeOutput object at 0x7ff42ee3ab60>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'personal_doc': '[PDOC]',
 'prefer_author_sort': False,
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': '/tmp/calibre_6.21.0_tmp_6mldf7c3/wr2k146h.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'share_not_sync': False,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: EPUB Input running
on /tmp/calibre_6.21.0_tmp_6mldf7c3/uvgxvj4x.epub
EPUB appears to be invalid ZIP file, trying a more forgiving ZIP parser
Traceback (most recent call last):
  File "calibre/utils/zipfile.py", line 1169, in _extract_member
  File "shutil.py", line 198, in copyfileobj
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/ebooks/conversion/plugins/epub_input.py", line 260, in convert
  File "calibre/utils/zipfile.py", line 1113, in extractall
  File "calibre/utils/zipfile.py", line 1097, in extract
  File "calibre/utils/zipfile.py", line 1176, in _extract_member
  File "shutil.py", line 198, in copyfileobj
OSError: [Errno 28] No space left on device

Traceback (most recent call last):


During handling of the above exception, another exception occurred:



During handling of the above exception, another exception occurred:
```

**Comment by Erick555** [comment]
The actual error is:

> OSError: [Errno 28] No space left on device

I guess this is either very big ebook or yours `XDG_RUNTIME_DIR` was filled up with something. You may try it again on fresh boot.

**Comment by Noonealamaison** [comment]
I've received the same "OSError: [Errno 28] No space left on device" doing a conversion of a 500MB book.

I ended up adding a 64G swapfile and increased the size of XDG_RUNTIME_DIR (/run/user/1000) from it's default 1.6G to 64G. The conversion then worked though it used 33GB of space in the XDG_RUNTIME_DIR.

I don't think modifying the XDG_RUNTIME_DIR size is realistic for a non technical user to do.
Instead I suggest setting the CALIBRE_TEMP_DIR environment variable to a disk based location in the flatpak.

I tested this by setting it using flatseal as below and it worked fine.
CALIBRE_TEMP_DIR=/home/homeuser/.var/app/com.calibre_ebook.calibre/cache/tmp
