### ISSUE TITLE
cannot run DeACSM plugin

### ISSUE THREAD

**Issue by LaHaine** [flathub/com.calibre_ebook.calibre#189]
This is with flatpak calibre 6.26.0 on Ubuntu 22.04. I cannot install the DeACSM plugin any more. This is working fine with the upstream installer version of calibre:
```
Traceback (most recent call last):
  File "calibre_plugins.deacsm.__init__", line 226, in initialize
    from libadobe import createDeviceKeyFile, update_account_path, sendHTTPRequest
  File "/home/user/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeACSM.zip/libadobe.py", line 59, in <module>
    from oscrypto import keys
  File "/home/user/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/keys.py", line 5, in <module>
    from ._asymmetric import parse_certificate, parse_private, parse_public
  File "/home/user/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/home/user/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/home/user/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/util.py", line 14, in <module>
    from ._openssl.util import rand_bytes
  File "/home/user/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/util.py", line 6, in <module>
    from ._libcrypto import libcrypto, libcrypto_version_info, handle_openssl_error
  File "/home/user/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto.py", line 24, in <module>
    from ._libcrypto_ctypes import (
  File "/home/user/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto_ctypes.py", line 47, in <module>
    raise LibraryNotFoundError('Error detecting the version of libcrypto')
oscrypto.errors.LibraryNotFoundError: Error detecting the version of libcrypto
Failed to initialize plugin: DeACSM (0, 0, 16)
Failed to initialize plugin: '/home/user/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeACSM.zip'

```

**Comment by LaHaine** [comment]
Here's the error on Alma Linux 9.2:
```

Traceback (most recent call last):
  File "calibre_plugins.deacsm.__init__", line 184, in initialize
    from calibre_plugins.deacsm.libadobe import createDeviceKeyFile, update_account_path
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.deacsm.libadobe", line 29, in <module>
    from oscrypto import keys
  File "/home/user/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/keys.py", line 5, in <module>
    from ._asymmetric import parse_certificate, parse_private, parse_public
  File "/home/user/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/home/user/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/home/user/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/util.py", line 14, in <module>
    from ._openssl.util import rand_bytes
  File "/home/user/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/util.py", line 6, in <module>
    from ._libcrypto import libcrypto, libcrypto_version_info, handle_openssl_error
  File "/home/user/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto.py", line 15, in <module>
    from ._libcrypto_ctypes import (
  File "/home/user/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto_ctypes.py", line 47, in <module>
    raise LibraryNotFoundError('Error detecting the version of libcrypto')
oscrypto.errors.LibraryNotFoundError: Error detecting the version of libcrypto

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.deacsm.__init__", line 187, in initialize
    from libadobe import createDeviceKeyFile, update_account_path
ModuleNotFoundError: No module named 'libadobe'
Failed to initialize plugin: DeACSM (0, 0, 15)
Failed to initialize plugin: '/home/user/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeACSM.zip'

```

**Comment by zhanglix** [comment]
if your openssl version has multiple digits in any of the three version parts, like 'Openssl 3.0.15', where 15 has two digits, then you can fix this issue by adding '+' after each '\\d' in the regex pattern in file modules/oscrypto/oscrypto/_openssl/_libcrypto_ctypes.py", line 43


```python
version_match = re.search('\\b(\\d+\\.\\d+\\.\\d+[a-z]*)\\b', version_string)
```
