### ISSUE TITLE
can't mount kindle .. altho it has mounted the kindle

### ISSUE THREAD

**Issue by japrogramer** [flathub/com.calibre_ebook.calibre#9]
First i try to allow the session-bus

```
▶ flatpak --socket=session-bus --device=all run com.calibre_ebook.calibre
Udisks mount call failed:
Traceback (most recent call last):
  File "site-packages/calibre/devices/usbms/device.py", line 554, in do_mount
  File "site-packages/calibre/devices/udisks.py", line 188, in mount
  File "site-packages/calibre/devices/udisks.py", line 183, in get_udisks1
EnvironmentError: UDisks not available on your system
Udisks mount call failed:
Traceback (most recent call last):
  File "site-packages/calibre/devices/usbms/device.py", line 554, in do_mount
  File "site-packages/calibre/devices/udisks.py", line 188, in mount
  File "site-packages/calibre/devices/udisks.py", line 183, in get_udisks1
EnvironmentError: UDisks not available on your system
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x7fd5aa2bc410>
Traceback (most recent call last):
  File "site-packages/calibre/gui2/device.py", line 198, in do_connect
  File "site-packages/calibre/devices/usbms/device.py", line 826, in open
  File "site-packages/calibre/devices/usbms/device.py", line 580, in open_linux
DeviceError: Unable to mount main memory (Error code: 1)

Udisks mount call failed:
Traceback (most recent call last):
  File "site-packages/calibre/devices/usbms/device.py", line 554, in do_mount
  File "site-packages/calibre/devices/udisks.py", line 188, in mount
  File "site-packages/calibre/devices/udisks.py", line 183, in get_udisks1
EnvironmentError: UDisks not available on your system
Udisks mount call failed:
Traceback (most recent call last):
  File "site-packages/calibre/devices/usbms/device.py", line 554, in do_mount
  File "site-packages/calibre/devices/udisks.py", line 188, in mount
  File "site-packages/calibre/devices/udisks.py", line 183, in get_udisks1
EnvironmentError: UDisks not available on your system
Udisks mount call failed:
Traceback (most recent call last):
  File "site-packages/calibre/devices/usbms/device.py", line 554, in do_mount
  File "site-packages/calibre/devices/udisks.py", line 188, in mount
  File "site-packages/calibre/devices/udisks.py", line 183, in get_udisks1
EnvironmentError: UDisks not available on your system
```
I have a little bit more luck with the system bus

but the device gets mounted in the hosts /run/media dir and not in the flatpaks
and it leads to a race condition or something 
```
▶ flatpak --socket=system-bus --device=all run com.calibre_ebook.calibre
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x7f6aa6b38410>
Traceback (most recent call last):
  File "site-packages/calibre/gui2/device.py", line 198, in do_connect
  File "site-packages/calibre/devices/usbms/device.py", line 823, in open
  File "site-packages/calibre/devices/usbms/device.py", line 577, in open_linux
  File "site-packages/calibre/devices/usbms/device.py", line 565, in mount
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

Udisks mount call failed:
Traceback (most recent call last):
  File "site-packages/calibre/devices/usbms/device.py", line 554, in do_mount
  File "site-packages/calibre/devices/udisks.py", line 189, in mount
  File "site-packages/calibre/devices/udisks.py", line 139, in mount
  File "site-packages/dbus/proxies.py", line 145, in __call__
  File "site-packages/dbus/connection.py", line 651, in call_blocking
DBusException: org.freedesktop.UDisks2.Error.AlreadyMounted: Device /dev/sdb1 is already mounted at `/run/media/archangel/Kindle'.

Udisks mount call failed:
Traceback (most recent call last):
  File "site-packages/calibre/devices/usbms/device.py", line 554, in do_mount
  File "site-packages/calibre/devices/udisks.py", line 189, in mount
  File "site-packages/calibre/devices/udisks.py", line 139, in mount
  File "site-packages/dbus/proxies.py", line 145, in __call__
  File "site-packages/dbus/connection.py", line 651, in call_blocking
DBusException: org.freedesktop.UDisks2.Error.AlreadyMounted: Device /dev/sdb1 is already mounted at `/run/media/archangel/Kindle'.

Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x7f6aa6b38410>
Traceback (most recent call last):
  File "site-packages/calibre/gui2/device.py", line 198, in do_connect
  File "site-packages/calibre/devices/usbms/device.py", line 826, in open
  File "site-packages/calibre/devices/usbms/device.py", line 580, in open_linux
DeviceError: Unable to mount main memory (Error code: 1)

Udisks mount call failed:
Traceback (most recent call last):
  File "site-packages/calibre/devices/usbms/device.py", line 554, in do_mount
  File "site-packages/calibre/devices/udisks.py", line 189, in mount
  File "site-packages/calibre/devices/udisks.py", line 139, in mount
  File "site-packages/dbus/proxies.py", line 145, in __call__
  File "site-packages/dbus/connection.py", line 651, in call_blocking
DBusException: org.freedesktop.UDisks2.Error.AlreadyMounted: Device /dev/sdb1 is already mounted at `/run/media/archangel/Kindle'.

Udisks mount call failed:
Traceback (most recent call last):
  File "site-packages/calibre/devices/usbms/device.py", line 554, in do_mount
  File "site-packages/calibre/devices/udisks.py", line 189, in mount
  File "site-packages/calibre/devices/udisks.py", line 139, in mount
  File "site-packages/dbus/proxies.py", line 145, in __call__
  File "site-packages/dbus/connection.py", line 651, in call_blocking
DBusException: org.freedesktop.UDisks2.Error.AlreadyMounted: Device /dev/sdb1 is already mounted at `/run/media/archangel/Kindle'.

```

**Comment by japrogramer** [comment]
ah, was able to make work with
`
flatpak --socket=system-bus --device=all --filesystem=/run/media/archangel/Kindle run com.calibre_ebook.calibre`

but should be documented so not to confuse novice users

**Comment by ghisvail** [comment]
@japrogramer Any idea what's actionable on my end?

**Comment by TingPing** [comment]
Change `home` to `host` for permissions would be a step. `system-bus` is certainly wrong. `device=all` may be needed.

**Comment by hpio** [comment]
I am having the exact same issue, and @japrogramer silution doesnt work for me:

```
 › flatpak --socket=system-bus --device=all --filesystem=/run/media/piotr/Kindle run com.calibre_ebook.calibre                                                                                                                                                                ~
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x7f2ba1db9d90>
Traceback (most recent call last):
  File "site-packages/calibre/gui2/device.py", line 198, in do_connect
  File "site-packages/calibre/devices/usbms/device.py", line 823, in open
  File "site-packages/calibre/devices/usbms/device.py", line 577, in open_linux
  File "site-packages/calibre/devices/usbms/device.py", line 565, in mount
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Any ideas?

**Comment by japrogramer** [comment]
@hpio 
looks like it was mounted under Kindle2 instead of Kindle
try this
```
flatpak --socket=system-bus --device=all --filesystem=/run/media/piotr run com.calibre_ebook.calibre
```

if calibre doesn't auto detect even mounting, I found that closing and starting it again, without disconnecting the kindle works.

**Comment by Iolaum** [comment]
I have the same problem using flatpaks, installed from Alex Larsson's ppa, on Ubuntu Mate 18.04. I tried the two solutions mentioned here, while kindle was already mounted but with no success :(

Logs:

```
$ flatpak --socket=system-bus --device=all --filesystem=/run/media/nikolaos/Kindle run com.calibre_ebook.calibre
QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries.
QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries.
Udisks mount call failed:
Traceback (most recent call last):
  File "site-packages/calibre/devices/usbms/device.py", line 554, in do_mount
  File "site-packages/calibre/devices/udisks.py", line 189, in mount
  File "site-packages/calibre/devices/udisks.py", line 139, in mount
  File "site-packages/dbus/proxies.py", line 145, in __call__
  File "site-packages/dbus/connection.py", line 651, in call_blocking
DBusException: org.freedesktop.UDisks2.Error.AlreadyMounted: Device /dev/sdc1 is already mounted at `/media/nikolaos/Kindle'.

Udisks mount call failed:
Traceback (most recent call last):
  File "site-packages/calibre/devices/usbms/device.py", line 554, in do_mount
  File "site-packages/calibre/devices/udisks.py", line 189, in mount
  File "site-packages/calibre/devices/udisks.py", line 139, in mount
  File "site-packages/dbus/proxies.py", line 145, in __call__
  File "site-packages/dbus/connection.py", line 651, in call_blocking
DBusException: org.freedesktop.UDisks2.Error.AlreadyMounted: Device /dev/sdc1 is already mounted at `/media/nikolaos/Kindle'.

Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x7f3116c404d0>
Traceback (most recent call last):
  File "site-packages/calibre/gui2/device.py", line 198, in do_connect
  File "site-packages/calibre/devices/usbms/device.py", line 826, in open
  File "site-packages/calibre/devices/usbms/device.py", line 580, in open_linux
DeviceError: Unable to mount main memory (Error code: 1)

Udisks mount call failed:
Traceback (most recent call last):
  File "site-packages/calibre/devices/usbms/device.py", line 554, in do_mount
  File "site-packages/calibre/devices/udisks.py", line 189, in mount
  File "site-packages/calibre/devices/udisks.py", line 139, in mount
  File "site-packages/dbus/proxies.py", line 145, in __call__
  File "site-packages/dbus/connection.py", line 651, in call_blocking
DBusException: org.freedesktop.UDisks2.Error.AlreadyMounted: Device /dev/sdc1 is already mounted at `/media/nikolaos/Kindle'.

Udisks mount call failed:
Traceback (most recent call last):
  File "site-packages/calibre/devices/usbms/device.py", line 554, in do_mount
  File "site-packages/calibre/devices/udisks.py", line 189, in mount
  File "site-packages/calibre/devices/udisks.py", line 139, in mount
  File "site-packages/dbus/proxies.py", line 145, in __call__
  File "site-packages/dbus/connection.py", line 651, in call_blocking
DBusException: org.freedesktop.UDisks2.Error.AlreadyMounted: Device /dev/sdc1 is already mounted at `/media/nikolaos/Kindle'.

Udisks mount call failed:
Traceback (most recent call last):
  File "site-packages/calibre/devices/usbms/device.py", line 554, in do_mount
  File "site-packages/calibre/devices/udisks.py", line 189, in mount
  File "site-packages/calibre/devices/udisks.py", line 139, in mount
  File "site-packages/dbus/proxies.py", line 145, in __call__
  File "site-packages/dbus/connection.py", line 651, in call_blocking
DBusException: org.freedesktop.UDisks2.Error.AlreadyMounted: Device /dev/sdc1 is already mounted at `/media/nikolaos/Kindle'.

Udisks mount call failed:
Traceback (most recent call last):
  File "site-packages/calibre/devices/usbms/device.py", line 554, in do_mount
  File "site-packages/calibre/devices/udisks.py", line 189, in mount
  File "site-packages/calibre/devices/udisks.py", line 139, in mount
  File "site-packages/dbus/proxies.py", line 145, in __call__
  File "site-packages/dbus/connection.py", line 651, in call_blocking
DBusException: org.freedesktop.UDisks2.Error.AlreadyMounted: Device /dev/sdc1 is already mounted at `/media/nikolaos/Kindle'.

```

and 

```
$ flatpak --socket=system-bus --device=all --filesystem=/run/media/nikolaos run com.calibre_ebook.calibre
QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries.
QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries.
Udisks mount call failed:
Traceback (most recent call last):
  File "site-packages/calibre/devices/usbms/device.py", line 554, in do_mount
  File "site-packages/calibre/devices/udisks.py", line 189, in mount
  File "site-packages/calibre/devices/udisks.py", line 139, in mount
  File "site-packages/dbus/proxies.py", line 145, in __call__
  File "site-packages/dbus/connection.py", line 651, in call_blocking
DBusException: org.freedesktop.UDisks2.Error.AlreadyMounted: Device /dev/sdc1 is already mounted at `/media/nikolaos/Kindle'.

Udisks mount call failed:
Traceback (most recent call last):
  File "site-packages/calibre/devices/usbms/device.py", line 554, in do_mount
  File "site-packages/calibre/devices/udisks.py", line 189, in mount
  File "site-packages/calibre/devices/udisks.py", line 139, in mount
  File "site-packages/dbus/proxies.py", line 145, in __call__
  File "site-packages/dbus/connection.py", line 651, in call_blocking
DBusException: org.freedesktop.UDisks2.Error.AlreadyMounted: Device /dev/sdc1 is already mounted at `/media/nikolaos/Kindle'.

Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x7fe0a78024d0>
Traceback (most recent call last):
  File "site-packages/calibre/gui2/device.py", line 198, in do_connect
  File "site-packages/calibre/devices/usbms/device.py", line 826, in open
  File "site-packages/calibre/devices/usbms/device.py", line 580, in open_linux
DeviceError: Unable to mount main memory (Error code: 1)


```

**Comment by japrogramer** [comment]
@Iolaum use this command
`$ flatpak --socket=system-bus --device=all --filesystem=/run/media/nikolaos run com.calibre_ebook.calibre`
and if it gives you something like this
```
eedesktop.UDisks2.Error.AlreadyMounted: Device /dev/sdc1 is already mounted at `/media/nikolaos/Kindle'.
```
close the application, and run it again. Don't disconnect the Kindle

**Comment by Iolaum** [comment]
I am still getting this error after closing and re-opening the application again. Tried it by having the kindle mounted before first try and by mounting it after I opened calibre for the first time. Both times when I open calibre for the second time I still get the error.

**Comment by japrogramer** [comment]
@Iolaum ok, but in the calibre interface can you see the device?

**Comment by Iolaum** [comment]
No I don't see it there either :(

**Comment by Iolaum** [comment]
I found it out :) 

We are probably using different distributions (@japrogramer ). For my case (Ubuntu MATE 18.04) the correct command was:
```
$ flatpak --socket=system-bus --device=all --filesystem=/media/nikolaos run com.calibre_ebook.calibre
```

**Comment by japrogramer** [comment]
ok, run lsblk in the host
```
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 238.5G  0 disk 
├─sda1   8:1    0   500M  0 part /boot
├─sda2   8:2    0    30G  0 part /
└─sda3   8:3    0   208G  0 part /home
sdb      8:16   1  27.3G  0 disk /run/media/archangel/Kindle
```
and in the flatpak namespace

```
▶ flatpak --socket=system-bus --device=all --filesystem=/run/media/archangel/ -d --command=sh run com.calibre_ebook.calibre                                                                                  39%
sh-4.4$ ls
 BAK   Code   Desktop   Documents   Downloads   error   mnt   Pictures   Talks   VENV  'VirtualBox VMs'
 sh-4.4$ lsblk
 NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
 sda      8:0    0 238.5G  0 disk
 ├─sda1   8:1    0   500M  0 part
 ├─sda2   8:2    0    30G  0 part /run/host/share/icons
 └─sda3   8:3    0   208G  0 part /run/host/user-fonts-cache
 sdb      8:16   1  27.3G  0 disk /run/media/archangel/Kindle
 sh-4.4$ ls
```

They should both have the Kindle in the same dir

**Comment by japrogramer** [comment]
@Iolaum ah, yeah, im using arch. Good to hear.

**Comment by Iolaum** [comment]
This appears to have been fixed in the latest update. :)

**Comment by japrogramer** [comment]
Hmm, sort off .. I still need to pass the system-bus

```
▶ flatpak run com.calibre_ebook.calibre                                                                                                                                                                         ∞
Udisks mount call failed:
Traceback (most recent call last):
  File "site-packages/calibre/devices/usbms/device.py", line 554, in do_mount
  File "site-packages/calibre/devices/udisks.py", line 188, in mount
  File "site-packages/calibre/devices/udisks.py", line 183, in get_udisks1
EnvironmentError: UDisks not available on your system
Udisks mount call failed:
Traceback (most recent call last):
  File "site-packages/calibre/devices/usbms/device.py", line 554, in do_mount
  File "site-packages/calibre/devices/udisks.py", line 188, in mount
  File "site-packages/calibre/devices/udisks.py", line 183, in get_udisks1
EnvironmentError: UDisks not available on your system
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x7fe573da2f10>
Traceback (most recent call last):
  File "site-packages/calibre/gui2/device.py", line 198, in do_connect
  File "site-packages/calibre/devices/usbms/device.py", line 826, in open
  File "site-packages/calibre/devices/usbms/device.py", line 580, in open_linux
DeviceError: Unable to mount main memory (Error code: 1)

Udisks mount call failed:
Traceback (most recent call last):
  File "site-packages/calibre/devices/usbms/device.py", line 554, in do_mount
  File "site-packages/calibre/devices/udisks.py", line 188, in mount
  File "site-packages/calibre/devices/udisks.py", line 183, in get_udisks1
EnvironmentError: UDisks not available on your system
^C

~                                                                                                                                                                                                                 ⍉
▶ flatpak --socket=system-bus run com.calibre_ebook.calibre                                                                                                                                                    ∞


```

**Comment by NeroVanbiervliet** [comment]
Also fixed in my case!

**Comment by Iolaum** [comment]
I noticed that calibre asked for host access in the update before it started working.

@japrogramer Could this (socket access requirement) then be related to how the flatpaks are installed/configured between Ubuntu and Arch or how the distributions are built?

**Comment by sat3ll** [comment]
@japrogramer Can you try:
`flatpak run --system-talk-name=org.freedesktop.UDisks2 com.calibre_ebook.calibre`

**Comment by japrogramer** [comment]
@sat3ll yes that worked.
